### ISSUE TITLE
Create UI mockups

### ISSUE THREAD

**Issue by andreafmenezes** [rossanafmenezes/Kakelandet_My_Cookbook#2]

**Comment by rossanafmenezes** [comment]
Mockup added [here](https://design.penpot.app/#/view/4efc6486-12af-80f1-8001-ac1294b52819?page-id=4efc6486-12af-80f1-8001-ac129c07f70e&section=interactions&index=0&share-id=39eb6d3d-9932-80bd-8001-ac5ccaaac0d4)

<img width="727" alt="Screen Shot 2022-11-29 at 6 06 07 PM" src="https://user-images.githubusercontent.com/30724184/204595274-0691ff75-5ca3-4e7e-9f87-06e8d5ed4876.png">

<img width="711" alt="Screen Shot 2022-11-29 at 5 59 45 PM" src="https://user-images.githubusercontent.com/30724184/204594980-368e1f2f-519f-4899-8b78-6876253ae192.png">
